[build-system]
requires = [
    "setuptools",
    "wheel",
    ]
build-backend = "setuptools.build_meta"

[project]
name = "roadshow-diffusion"
version = "0.5"
dependencies = [
    "numpy",
]

[tool.setuptools]
packages = ["roadshow_diffusion"]
